//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinUI.Properties
{
    using System;
    using System.Drawing;
    using System.Resources;
    using System.Globalization;
    using System.CodeDom.Compiler;
    using System.Diagnostics;
    using System.Runtime.CompilerServices;
    using System.ComponentModel;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    internal class Resources
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal Resources() { }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    resourceMan = new ResourceManager("WinUI.Properties.Resources", typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static Bitmap alarm_24px => (Bitmap)ResourceManager.GetObject("alarm_24px", resourceCulture);
        internal static Bitmap azimuth_24px => (Bitmap)ResourceManager.GetObject("azimuth_24px", resourceCulture);
        internal static Bitmap cancel => (Bitmap)ResourceManager.GetObject("cancel", resourceCulture);
        internal static Bitmap Checkmark_12px => (Bitmap)ResourceManager.GetObject("Checkmark_12px", resourceCulture);
        internal static Bitmap filled_alarm_24px => (Bitmap)ResourceManager.GetObject("filled_alarm_24px", resourceCulture);
        internal static Bitmap filled_azimuth_24px => (Bitmap)ResourceManager.GetObject("filled_azimuth_24px", resourceCulture);
        internal static Bitmap filled_home_24px => (Bitmap)ResourceManager.GetObject("filled_home_24px", resourceCulture);
        internal static Bitmap filled_monitor_24px => (Bitmap)ResourceManager.GetObject("filled_monitor_24px", resourceCulture);
        internal static Bitmap filled_save_24px => (Bitmap)ResourceManager.GetObject("filled_save_24px", resourceCulture);
        internal static Bitmap filled_settings_24px => (Bitmap)ResourceManager.GetObject("filled_settings_24px", resourceCulture);
        internal static Bitmap home_24px => (Bitmap)ResourceManager.GetObject("home_24px", resourceCulture);
        internal static Bitmap monitor_24px => (Bitmap)ResourceManager.GetObject("monitor_24px", resourceCulture);
        internal static Bitmap save_24px => (Bitmap)ResourceManager.GetObject("save_24px", resourceCulture);
        internal static Bitmap settings_24px => (Bitmap)ResourceManager.GetObject("settings_24px", resourceCulture);
    }
}
